name: Deploy and Test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        name: Checkout

      - name: Build docker image
        run: docker build -f ./dev/build/Dockerfile -t mauzzz0/wiki-js:latest .

      - name: Push docker image
        run: docker push mauzzz0/wiki-js:latest

#      - name: Update and restart containers
#       run: |
#          cd C:\wiki-compose
#          docker pull mauzzz0/wiki-js:latest
#          docker compose down
#          docker compose up -d
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '22'
#
#
#      - name: Install yarn
#        run: npm i -g yarn
#
#      - name: Install dependencies
#        run: yarn
#
#      - name: Patch dependencies
#        run: yarn patch-package

#      - name: Build project
#        run: yarn build
